"""core mvp domain models

Revision ID: 1e302475a174
Revises: 
Create Date: 2026-08-19 02:59:55.236237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e302475a174'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector: required before the 'memories' table's embedding column (vector type)
    # can be created. Not part of autogenerate's detection — added by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR email IS NOT NULL', name='ck_customers_has_contact_method'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'email', name='uq_customers_restaurant_email'),
    sa.UniqueConstraint('restaurant_id', 'phone', name='uq_customers_restaurant_phone')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_restaurant_type_occurred', 'events', ['restaurant_id', 'event_type', 'occurred_at'], unique=False)
    op.create_index('ix_events_unhandled', 'events', ['id'], unique=False, postgresql_where=sa.text('NOT handled'))
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok','low','out_of_stock')", name='ck_inventory_items_status_valid'),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_inventory_items_threshold_non_negative'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_items_quantity_non_negative'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_inventory_items_restaurant_name')
    )
    op.create_index('ix_inventory_items_restaurant_status', 'inventory_items', ['restaurant_id', 'status'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_menu_items_price_non_negative'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_items_restaurant_category', 'menu_items', ['restaurant_id', 'category'], unique=False)
    op.create_index('uq_menu_items_restaurant_name_available', 'menu_items', ['restaurant_id', 'name'], unique=True, postgresql_where=sa.text('is_available'))
    op.create_table('restaurant_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('seat_capacity', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seat_capacity > 0', name='ck_restaurant_tables_seat_capacity_positive'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_restaurant_tables_restaurant_label_active', 'restaurant_tables', ['restaurant_id', 'label'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('server','cook','host','bartender','manager_on_duty','other')", name='ck_staff_role_valid'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_restaurant_active', 'staff', ['restaurant_id', 'is_active'], unique=False)
    op.create_table('staff_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_staff_count', sa.SmallInteger(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('staffed','understaffed')", name='ck_staff_shifts_status_valid'),
    sa.CheckConstraint('end_at > start_at', name='ck_staff_shifts_end_after_start'),
    sa.CheckConstraint('required_staff_count > 0', name='ck_staff_shifts_required_count_positive'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role = 'manager'", name='ck_users_role_manager_only'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'email', name='uq_users_restaurant_email')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('initiated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('triggering_event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome_summary', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(trigger_type = 'manager_request' AND initiated_by_user_id IS NOT NULL AND triggering_event_id IS NULL) OR (trigger_type = 'event' AND triggering_event_id IS NOT NULL AND initiated_by_user_id IS NULL)", name='ck_agent_runs_trigger_consistency'),
    sa.CheckConstraint("status IN ('running','completed','failed')", name='ck_agent_runs_status_valid'),
    sa.CheckConstraint("trigger_type IN ('manager_request','event')", name='ck_agent_runs_trigger_type_valid'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_correlation_id', 'agent_runs', ['correlation_id'], unique=False)
    op.create_index('ix_agent_runs_parent_run_id', 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index('ix_agent_runs_restaurant_agent_started', 'agent_runs', ['restaurant_id', 'agent_name', 'started_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('proposed_by_tool', sa.String(), nullable=False),
    sa.Column('proposed_by_agent_run_id', sa.UUID(), nullable=False),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status IN ('approved','rejected') AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL) OR (status IN ('pending','expired'))", name='ck_approvals_decision_consistency'),
    sa.CheckConstraint("domain IN ('reservation','inventory','staffing','purchase')", name='ck_approvals_domain_valid'),
    sa.CheckConstraint("status IN ('pending','approved','rejected','expired')", name='ck_approvals_status_valid'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_agent_run_id'], ['agent_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_proposed_by_agent_run', 'approvals', ['proposed_by_agent_run_id'], unique=False)
    op.create_index('ix_approvals_restaurant_status', 'approvals', ['restaurant_id', 'status'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('scope_key', sa.String(), sa.Computed("COALESCE(customer_id::text, agent_name, 'restaurant')", persisted=True), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("memory_type IN ('CUSTOMER_PREFERENCE','BUSINESS_RULE','MANAGER_PREFERENCE','PAST_DECISION','OPERATIONAL_FACT','AGENT_EXPERIENCE')", name='ck_memories_memory_type_valid'),
    sa.CheckConstraint("source IN ('manager_stated','agent_inferred','system_derived')", name='ck_memories_source_valid'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_memories_confidence_range'),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_memories_importance_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_embedding_hnsw', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memories_restaurant_agent', 'memories', ['restaurant_id', 'agent_name'], unique=False, postgresql_where=sa.text('agent_name IS NOT NULL AND is_active'))
    op.create_index('ix_memories_restaurant_customer', 'memories', ['restaurant_id', 'customer_id'], unique=False, postgresql_where=sa.text('customer_id IS NOT NULL AND is_active'))
    op.create_index('ix_memories_restaurant_type_active', 'memories', ['restaurant_id', 'memory_type', 'is_active'], unique=False)
    op.create_index('uq_memories_active_scope_topic', 'memories', ['restaurant_id', 'memory_type', 'scope_key', 'topic'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','tool_call','tool_result','system')", name='ck_agent_messages_role_valid'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_agent_messages_run_sequence', 'agent_messages', ['run_id', 'sequence_number'], unique=True)
    op.create_table('purchase_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','pending_approval','approved','rejected','fulfilled','cancelled')", name='ck_purchase_requests_status_valid'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_purchase_requests_cost_non_negative'),
    sa.CheckConstraint('requested_quantity > 0', name='ck_purchase_requests_quantity_positive'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_requests_restaurant_status', 'purchase_requests', ['restaurant_id', 'status'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('party_size', sa.SmallInteger(), nullable=False),
    sa.Column('requested_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_via', sa.String(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_via IN ('manager_request','event')", name='ck_reservations_created_via_valid'),
    sa.CheckConstraint("status IN ('requested','booked','modified','cancelled','completed','no_show')", name='ck_reservations_status_valid'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_reservations_duration_positive'),
    sa.CheckConstraint('party_size > 0', name='ck_reservations_party_size_positive'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_active_by_restaurant', 'reservations', ['restaurant_id', 'status'], unique=False, postgresql_where=sa.text("status IN ('requested','booked','modified')"))
    op.create_index('ix_reservations_customer', 'reservations', ['customer_id'], unique=False)
    op.create_index('ix_reservations_restaurant_requested_time', 'reservations', ['restaurant_id', 'requested_time'], unique=False)
    op.create_index('ix_reservations_table_requested_time', 'reservations', ['table_id', 'requested_time'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['staff_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'staff_id', name='uq_shift_assignments_shift_staff')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('resulting_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('purchase_request_id', sa.UUID(), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_agent_run_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("change_type IN ('delivery','waste','correction','purchase_received','other')", name='ck_inventory_transactions_change_type_valid'),
    sa.CheckConstraint('quantity_delta <> 0', name='ck_inventory_transactions_delta_nonzero'),
    sa.CheckConstraint('resulting_quantity >= 0', name='ck_inventory_transactions_resulting_non_negative'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_transactions_purchase_request', 'inventory_transactions', ['purchase_request_id'], unique=False, postgresql_where=sa.text('purchase_request_id IS NOT NULL'))
    op.create_index('ix_inventory_transactions_restaurant_item_recorded', 'inventory_transactions', ['restaurant_id', 'item_id', 'recorded_at'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), sa.Computed('quantity * unit_price', persisted=True), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_menu_item_sold_at', 'sales', ['menu_item_id', 'sold_at'], unique=False)
    op.create_index('ix_sales_restaurant_sold_at', 'sales', ['restaurant_id', 'sold_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_restaurant_sold_at', table_name='sales')
    op.drop_index('ix_sales_menu_item_sold_at', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_inventory_transactions_restaurant_item_recorded', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_purchase_request', table_name='inventory_transactions', postgresql_where=sa.text('purchase_request_id IS NOT NULL'))
    op.drop_table('inventory_transactions')
    op.drop_table('shift_assignments')
    op.drop_index('ix_reservations_table_requested_time', table_name='reservations')
    op.drop_index('ix_reservations_restaurant_requested_time', table_name='reservations')
    op.drop_index('ix_reservations_customer', table_name='reservations')
    op.drop_index('ix_reservations_active_by_restaurant', table_name='reservations', postgresql_where=sa.text("status IN ('requested','booked','modified')"))
    op.drop_table('reservations')
    op.drop_index('ix_purchase_requests_restaurant_status', table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index('uq_agent_messages_run_sequence', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('uq_memories_active_scope_topic', table_name='memories', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_memories_restaurant_type_active', table_name='memories')
    op.drop_index('ix_memories_restaurant_customer', table_name='memories', postgresql_where=sa.text('customer_id IS NOT NULL AND is_active'))
    op.drop_index('ix_memories_restaurant_agent', table_name='memories', postgresql_where=sa.text('agent_name IS NOT NULL AND is_active'))
    op.drop_index('ix_memories_embedding_hnsw', table_name='memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memories')
    op.drop_index('ix_approvals_restaurant_status', table_name='approvals')
    op.drop_index('ix_approvals_proposed_by_agent_run', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_agent_runs_restaurant_agent_started', table_name='agent_runs')
    op.drop_index('ix_agent_runs_parent_run_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_correlation_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('users')
    op.drop_table('staff_shifts')
    op.drop_index('ix_staff_restaurant_active', table_name='staff')
    op.drop_table('staff')
    op.drop_index('uq_restaurant_tables_restaurant_label_active', table_name='restaurant_tables', postgresql_where=sa.text('is_active'))
    op.drop_table('restaurant_tables')
    op.drop_index('uq_menu_items_restaurant_name_available', table_name='menu_items', postgresql_where=sa.text('is_available'))
    op.drop_index('ix_menu_items_restaurant_category', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_inventory_items_restaurant_status', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_events_unhandled', table_name='events', postgresql_where=sa.text('NOT handled'))
    op.drop_index('ix_events_restaurant_type_occurred', table_name='events')
    op.drop_table('events')
    op.drop_table('customers')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
