"""redesign approvals for risk levels and execution tracking

Revision ID: 3a9fe896c6d3
Revises: fbf678bce577
Create Date: 2026-08-19 08:35:47.759646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a9fe896c6d3'
down_revision: Union[str, Sequence[str], None] = 'fbf678bce577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_OLD_DECISION_CONSISTENCY = (
    "(status IN ('approved','rejected') AND decided_by_user_id IS NOT NULL "
    "AND decided_at IS NOT NULL) OR (status IN ('pending','expired'))"
)
_NEW_DECISION_CONSISTENCY = (
    "(status = 'approved' AND approved_at IS NOT NULL AND decided_by_user_id IS NOT NULL "
    "AND rejected_at IS NULL) "
    "OR (status = 'rejected' AND rejected_at IS NOT NULL AND decided_by_user_id IS NOT NULL "
    "AND approved_at IS NULL) "
    "OR (status IN ('pending','expired') AND approved_at IS NULL AND rejected_at IS NULL)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('action', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('agent_name', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('reason', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('approvals', sa.Column('risk_level', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approvals', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approvals', sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('approvals', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint('ck_approvals_risk_level_valid', 'approvals', "risk_level IN ('LOW','MEDIUM','HIGH')")
    op.drop_column('approvals', 'proposed_by_tool')
    op.drop_column('approvals', 'summary')
    op.drop_column('approvals', 'proposed_action')
    # dropping decided_at implicitly CASCADE-drops ck_approvals_decision_consistency
    # (it referenced that column), so only re-create it — don't also drop_constraint.
    op.drop_column('approvals', 'decided_at')
    op.create_check_constraint(
        'ck_approvals_decision_consistency', 'approvals', _NEW_DECISION_CONSISTENCY
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'executed_at')
    op.drop_column('approvals', 'execution_result')
    # dropping approved_at/rejected_at CASCADE-drops ck_approvals_decision_consistency
    # (it references them), same reasoning as upgrade() — re-create it afterward.
    op.drop_column('approvals', 'rejected_at')
    op.drop_column('approvals', 'approved_at')
    op.drop_constraint('ck_approvals_risk_level_valid', 'approvals', type_='check')
    op.drop_column('approvals', 'risk_level')
    op.drop_column('approvals', 'parameters')
    op.drop_column('approvals', 'reason')
    op.drop_column('approvals', 'agent_name')
    op.drop_column('approvals', 'action')
    op.add_column('approvals', sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('approvals', sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('approvals', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('approvals', sa.Column('proposed_by_tool', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_check_constraint(
        'ck_approvals_decision_consistency', 'approvals', _OLD_DECISION_CONSISTENCY
    )
    # ### end Alembic commands ###
