"""redesign events for event-driven architecture

Revision ID: 7563f16597f2
Revises: 3a9fe896c6d3
Create Date: 2026-08-19 09:32:24.081785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7563f16597f2'
down_revision: Union[str, Sequence[str], None] = '3a9fe896c6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('correlation_id', sa.UUID(), nullable=False))
    op.add_column('events', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('handler_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_events_restaurant_type_occurred'), table_name='events')
    op.create_index('ix_events_correlation_id', 'events', ['correlation_id'], unique=False)
    op.create_index('ix_events_entity_id', 'events', ['entity_id'], unique=False)
    op.create_index('ix_events_restaurant_type_created', 'events', ['restaurant_id', 'event_type', 'created_at'], unique=False)
    op.create_index('uq_events_idempotency_key', 'events', ['restaurant_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_check_constraint('ck_events_event_type_valid', 'events', "event_type IN ('reservation.created','reservation.modified','reservation.cancelled','inventory.updated','inventory.low','purchase.requested','purchase.approved','purchase.rejected','customer.updated','staffing.shortage_detected','approval.created','approval.completed')")
    op.drop_column('events', 'occurred_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('ck_events_event_type_valid', 'events', type_='check')
    op.drop_index('uq_events_idempotency_key', table_name='events', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_events_restaurant_type_created', table_name='events')
    op.drop_index('ix_events_entity_id', table_name='events')
    op.drop_index('ix_events_correlation_id', table_name='events')
    op.create_index(op.f('ix_events_restaurant_type_occurred'), 'events', ['restaurant_id', 'event_type', 'occurred_at'], unique=False)
    op.drop_column('events', 'handler_results')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'idempotency_key')
    op.drop_column('events', 'correlation_id')
    op.drop_column('events', 'entity_id')
    # ### end Alembic commands ###
