"""add workflow_runs and scheduled trigger_type

Revision ID: d945e4c60188
Revises: 7563f16597f2
Create Date: 2026-08-19 15:29:04.406925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd945e4c60188'
down_revision: Union[str, Sequence[str], None] = '7563f16597f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OLD_TRIGGER_TYPE_VALID = "trigger_type IN ('manager_request','event')"
_NEW_TRIGGER_TYPE_VALID = "trigger_type IN ('manager_request','event','scheduled')"

_OLD_TRIGGER_CONSISTENCY = (
    "(trigger_type = 'manager_request' AND initiated_by_user_id IS NOT NULL "
    "AND triggering_event_id IS NULL) OR "
    "(trigger_type = 'event' AND triggering_event_id IS NOT NULL "
    "AND initiated_by_user_id IS NULL)"
)
_NEW_TRIGGER_CONSISTENCY = (
    "(trigger_type = 'manager_request' AND initiated_by_user_id IS NOT NULL "
    "AND triggering_event_id IS NULL) OR "
    "(trigger_type = 'event' AND triggering_event_id IS NOT NULL "
    "AND initiated_by_user_id IS NULL) OR "
    "(trigger_type = 'scheduled' AND initiated_by_user_id IS NULL "
    "AND triggering_event_id IS NULL)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running','completed','failed')", name='ck_workflow_runs_status_valid'),
    sa.CheckConstraint("triggered_by IN ('scheduler','manual')", name='ck_workflow_runs_triggered_by_valid'),
    sa.CheckConstraint("workflow_type IN ('daily_briefing','inventory_monitoring','reservation_monitoring','staffing_monitoring')", name='ck_workflow_runs_workflow_type_valid'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_correlation_id', 'workflow_runs', ['correlation_id'], unique=False)
    op.create_index('ix_workflow_runs_restaurant_type_started', 'workflow_runs', ['restaurant_id', 'workflow_type', 'started_at'], unique=False)
    # Not auto-detected: the body of two agent_runs CHECK constraints changed
    # (a third trigger_type, 'scheduled', is now valid) even though their names didn't.
    op.drop_constraint('ck_agent_runs_trigger_consistency', 'agent_runs', type_='check')
    op.drop_constraint('ck_agent_runs_trigger_type_valid', 'agent_runs', type_='check')
    op.create_check_constraint('ck_agent_runs_trigger_type_valid', 'agent_runs', _NEW_TRIGGER_TYPE_VALID)
    op.create_check_constraint('ck_agent_runs_trigger_consistency', 'agent_runs', _NEW_TRIGGER_CONSISTENCY)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_agent_runs_trigger_consistency', 'agent_runs', type_='check')
    op.drop_constraint('ck_agent_runs_trigger_type_valid', 'agent_runs', type_='check')
    op.create_check_constraint('ck_agent_runs_trigger_type_valid', 'agent_runs', _OLD_TRIGGER_TYPE_VALID)
    op.create_check_constraint('ck_agent_runs_trigger_consistency', 'agent_runs', _OLD_TRIGGER_CONSISTENCY)
    op.drop_index('ix_workflow_runs_restaurant_type_started', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_correlation_id', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    # ### end Alembic commands ###
