"""add model_name to agent_runs

Revision ID: fbf678bce577
Revises: 1e302475a174
Create Date: 2026-08-19 04:27:56.022719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf678bce577'
down_revision: Union[str, Sequence[str], None] = '1e302475a174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('model_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'model_name')
    # ### end Alembic commands ###
